<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="Lac_Neouvielle.css" />
  <link rel="stylesheet" href="Lac_Neouvielle/Lac_Neouvielle.css" />
  <link rel="stylesheet" href="../style.css" />
  <title>Lacs de Neouvielle</title>
</head>

<body>
  <header>
    <img src="../src/images/logo_header.png" alt="logo du site" />
    <nav>
      <ul>
        <li><a href="../index.html"> Accueil</a></li>
        <li><a href="../Articles/articles.html"> Articles</a></li>
        <li><a href="#contact"> Contact</a></li>
      </ul>
    </nav>
  </header>
  <main class="container">
    <div class="flex-images">
      <img src="../src/Lacs_neouvielle/28.jpg" alt="" />
      <img src="../src/Lacs_neouvielle/20.jpg" alt="" />
      <img src="../src/Lacs_neouvielle/29.JPG" alt="" />
    </div>
    <h1>Lacs de Neouvielle</h1>
    <section class="slides">
      <div class="owl-carousel owl-theme">
        <div class="item img1"></div>
        <div class="item img2"></div>
        <div class="item img3"></div>
        <div class="item img4"></div>
        <div class="item img5"></div>
        <div class="item img6"></div>
        <div class="item img7"></div>
        <div class="item img8"></div>
        <div class="item img9"></div>
        <div class="item img10"></div>
      </div>
    </section>
    <section>
      <img class="map" src="../src/Lacs_neouvielle/16.jpg" alt="" />
      <p>
        Situé dans les Hautes-pyrénées, entre montagnes et lacs, la réserve de
        Neouvielle offre des paysages magnifiques. Il existe des lacs
        artificiels ainsi que des lacs naturels . Ces derniers ont été formés
        il y a des dizaines de milliers d’années par un verrou glaciaire.
        Outre ces très grands lacs, le site de Néouvielle regorge de dizaines
        de petits étangs baptisées ici les « laquettes ». Ce secteur des
        Pyrénées est sans doute l’un des plus beaux.
      </p>
      <p>
        Avec notre groupe, nous avons parcouru 16 km pendant 5 heures et 40
        minutes. Nous avons découvert des paysages magnifiques avec un beau
        temps qui a bien évidement embelli cette journée.
      </p>
    </section>
    <section class="grid">
      <div class="pictures">
        <img src="../src/Lacs_neouvielle/1.JPG" alt="" />
        <img src="../src/Lacs_neouvielle/2.JPG" alt="" />
        <img src="../src/Lacs_neouvielle/7.JPG" alt="" />
        <img src="../src/Lacs_neouvielle/9.JPG" alt="" />
        <img src="../src/Lacs_neouvielle/12.JPG" alt="" />
        <img src="../src/Lacs_neouvielle/17.JPG" alt="" />
      </div>
    </section>
    <article class="comments">
      <h2>Commentaires</h2>
      <table class="table-comments">
        <?php
        foreach ($comments as $comment) : ?>
          <tr>
            <td class="comments-infos">
              <p><?= $comment['pseudo'] ?></p>
              <p><?= $comment['created_at'] ?></p>
            </td>
            <td class="comments-message">
              <p><?= $comment['content'] ?></p>
            </td>
          </tr>
        <?php endforeach; ?>
      </table>
      <form method="POST" action="../comments.php" class="form-comments">
        <input type="hidden" name="id" value="3">
        <label for=" pseudo">Pseudo</label>
        <input type="text" name="pseudo" placeholder="Entrez votre pseudo" class="pseudo">
        <label for="message">Commentaire</label>
        <textarea name="message" id="message" cols="30" rows="10" class="message" placeholder="Entrez un commentaire"></textarea>
        <input class="button" type="submit" value="Envoyer">
      </form>
    </article>
  </main>
  <footer id="contact">
    <div class="footer-mail">
      <h2>Contactez-nous</h2>
      <i class="fa-solid fa-envelope fa-xl"></i>
      <a mailto="#">ast-loisir@gmail.com</a>
    </div>
    <div class="images-footer">
      <img src="../src/images/footer_1.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_2.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_3.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_4.jpg" alt="Paysage en randonnée" />
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="script.js"></script>
</body>

</html>