<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="Saint_saturnin.css" />
  <link rel="stylesheet" href="Saint_saturnin/Saint_saturnin.css" />
  <link rel="stylesheet" href="../style.css" />
  <title>Saint-Saturnin de Lucian</title>
</head>

<body>
  <header>
    <img src="../src/images/logo_header.png" alt="logo du site" />
    <nav>
      <ul>
        <li><a href="../index.html"> Accueil</a></li>
        <li><a href="../Articles/articles.html"> Articles</a></li>
        <li><a href="#contact"> Contact</a></li>
      </ul>
    </nav>
  </header>
  <main class="container">
    <h1>Saint-Saturnin de Lucian</h1>
    <section class="map">
      <div class="map-images">
        <img src="../src/Saint_saturnin/carte-saint_saturnin.png" alt="Saint-Saturnin de Lucian sur une carte de France" />
        <img class="panneau" src="../src/Saint_saturnin/panneau.jpg" alt="panneau Saint-Saturnin-de-Lucian" />
      </div>
    </section>
    <section class="informations">
      <img src="../src/Saint_saturnin/1.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
      <p>
        Saint-Saturnin-de-Lucian est une commune française située dans le nord
        du département de l'Hérault (34) en région Occitanie. Nous avons fait
        cette randonnée le Dimanche 27 Novembre avec 10 personnes. Nous avons
        pu découvrir les rochers des deux vierges et le canyon du diable
        (terre rouge). Dans l'ensemble, c'était magnifique !
      </p>
      <p>
        Un paysage semblable à celui de l'Ouest Américain, coloré, naturel et
        curieux. C'est un lieu parmi les plus intéressants de la région.
        Cependant, attention de ne pas vous perdre dans le canyon.
      </p>
    </section>
    <section>
      <div class="grid">
        <img src="../src/Saint_saturnin/6.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/8.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/9.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/14.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/11.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/20.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/3.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
        <img src="../src/Saint_saturnin/13.jpg" alt="paysage Saint-Saturnin-de-Lucian" />
      </div>
    </section>
    <article class="comments">
      <h2>Commentaires</h2>
      <table class="table-comments">
        <?php
        foreach ($comments as $comment) : ?>
          <tr>
            <td class="comments-infos">
              <p><?= $comment['pseudo'] ?></p>
              <p><?= $comment['created_at'] ?></p>
            </td>
            <td class="comments-message">
              <p><?= $comment['content'] ?></p>
            </td>
          </tr>
        <?php endforeach; ?>
      </table>
      <form method="POST" action="../comments.php" class="form-comments">
        <input type="hidden" name="id" value="1">
        <label for=" pseudo">Pseudo</label>
        <input type="text" name="pseudo" placeholder="Entrez votre pseudo" class="pseudo">
        <label for="message">Commentaire</label>
        <textarea name="message" id="message" cols="30" rows="10" class="message" placeholder="Entrez un commentaire"></textarea>
        <input class="button" type="submit" value="Envoyer">
      </form>
    </article>
  </main>
  <footer id="contact">
    <div class="footer-mail">
      <h2>Contactez-nous</h2>
      <i class="fa-solid fa-envelope fa-xl"></i>
      <a mailto="#">ast-loisir@gmail.com</a>
    </div>
    <div class="images-footer">
      <img src="../src/images/footer_1.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_2.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_3.jpg" alt="Paysage en randonnée" />
      <img src="../src/images/footer_4.jpg" alt="Paysage en randonnée" />
    </div>
  </footer>
</body>

</html>